### ISSUE TITLE
Blue slide-up animation bugged on correct answer

### ISSUE THREAD

**Issue by GirkovArpa** [GirkovArpa/slidercards#1]
The blue face should bounce into the card face, but it simply appears there:

![preview](https://i.imgur.com/ucIt5si.gif)

**Comment by 4silvertooth** [comment]
Hmm, the keyframes percentage need to chnage so that it slides up. Maybe ~25%~ 15% is too less for it to complete.

**Comment by GirkovArpa** [comment]
I'm tempted to say it's bugged because I don't see anything wrong with the CSS.  Maybe Sciter can't animate or transition `foreground-position` inside `@keyframes`?

**Update**

I've got the face to slide in using[ `foreground-position-top` inside `@keyframes`,](https://github.com/GirkovArpa/slidercards/commit/9fc69c8d19a0779afad020f2f1021a1166d00645) but the `bounce-in` transition effect seems to be ignored.

**Comment by 4silvertooth** [comment]
Just make another keyframe at 30% with foreground-position a bit below and then continue...that will display as a bounce...

**Comment by 4silvertooth** [comment]
How does this [commit](https://github.com/GirkovArpa/slidercards/commit/23dea13687d282412c505401e12d333ef118bb4d) look?

**Comment by GirkovArpa** [comment]
It's probably the best we can achieve using keyframes.  But it's not a perfectly faithful recreation of the effect since all the motion is now linear.  My preview GIF at the moment is false advertising :slightly_frowning_face:

____
**Edit**
You can see the effect I'm trying to replicate in [this](https://www.youtube.com/watch?v=G0udcNZCyu0&t=0m45s) YouTube video.

**Comment by 4silvertooth** [comment]
Oh i get it, when the face hits the top the whole card bounces, and not just the face image, made a new commit. What other things need attention?

**Comment by GirkovArpa** [comment]
I did not even realize the whole card bounced 😄 I like this change, thank you very much.

Now I'm waiting for next version of Sciter.JS so I can add sound effects.
