### ISSUE TITLE
Card reappears in center of screen 

### ISSUE THREAD

**Issue by GirkovArpa** [GirkovArpa/slidercards#2]
After sliding left off the screen, sometimes (unpredictably) the card will reappear for a brief instant in the center of the screen before the new card slides in from the left.

I presume this is a desynchronization between CSS framerate and JavaScript ticks.

**Comment by 4silvertooth** [comment]
If you reduce this time here https://github.com/GirkovArpa/slidercards/blob/bb11d3c8b70fd6a80a4f3cab6bc8c3bbe7081c8c/main.js#L79
It won't popup but I am still looking into it. After the keyframes are over it jumps back to the start of animation that's the problem.
